version: '3.8'

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mean_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: node:18-alpine
    restart: unless-stopped
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URI: mongodb://admin:${MONGODB_ROOT_PASSWORD}@mongodb:27017/meanapp?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongodb
    networks:
      - mean_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: node:18-alpine
    restart: unless-stopped
    working_dir: /app
    environment:
      NODE_ENV: ${NODE_ENV}
      API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    networks:
      - mean_network

volumes:
  mongodb_data:

networks:
  mean_network:
    driver: bridge